export type ProjectStatus = 'active' | 'archived' | 'experiment';
export type CoverTone = 'blue' | 'green' | 'orange' | 'purple' | 'red' | 'teal';

export type Project = {
  name: string;
  kind: string;
  url: string;
  year: string;
  status: ProjectStatus;
  description: string;
  detail: string;
  tech: string;
  role?: string;
  featured?: boolean;
  coverTone: CoverTone;
  logo?: string;
};

export type Experience = {
  id: string;
  organization: string;
  role: string;
  period: string;
  location: string;
  website?: string;
  logo?: string;
  description: string;
  highlights: string[];
  relatedProject?: string;
};

export type Award = {
  year: string;
  name: string;
  issuer?: string;
  description: string;
};

export type Photo = {
  id: string;
  title: string;
  album: string;
  section: 'Projects' | 'Achievements' | 'Acceptances' | 'Experiences & Events';
  src: string;
  date: string;
  caption: string;
  alt: string;
  kind: 'photo' | 'poster' | 'document';
  project?: string;
  achievement?: string;
  experience?: string;
};

export const profile = {
  name: 'Nurbek Alisherov',
  handle: 'uzalisherov',
  location: 'Uzbekistan',
  headline: 'AI builder, entrepreneur, and student',
  focus: 'Artificial Intelligence · Education · Startups',
  bio: 'I build technology and education projects, lead youth communities, and experiment with AI products. NurbekOS is a portfolio designed like the computer I wish every portfolio could be: something you can explore instead of scroll through.',
  computerName: 'NURBEK-XP',
  workgroup: 'BUILDERS',
  links: {
    website: 'https://alisherov.com',
    github: 'https://github.com/alisherovuz',
    linkedin: 'https://www.linkedin.com/in/uzalisherov/',
  },
};

export const projects: Project[] = [
  {
    name: 'EduGrands',
    kind: 'EdTech platform',
    url: 'https://edugrants.uz',
    year: 'Aug 2023 — present',
    status: 'active',
    role: 'Founder & CEO',
    featured: true,
    coverTone: 'blue',
    logo: '/media/projects/edugrands/logo.webp',
    description: 'A scholarship-discovery platform helping students in Uzbekistan find verified international opportunities.',
    detail: 'The project grew into a web platform, Telegram community and EduCast interview series. Recent public updates place the ecosystem at 50,000+ users.',
    tech: 'Product · Community · Partnerships · Web',
  },
  {
    name: 'Empira',
    kind: 'AI / EdTech product',
    url: 'https://empira.uz',
    year: 'Sept 2026 — present',
    status: 'active',
    role: 'Co-Founder & CEO',
    featured: true,
    coverTone: 'purple',
    logo: '/media/projects/empira/logo.webp',
    description: 'An AI virtual laboratory that turns textbook pages into interactive 3D experiments with an Uzbek AI tutor.',
    detail: 'Built from scratch in 72 hours with JaydariTech and won 1st place in the EdTech track at the National AI Hackathon.',
    tech: 'AI · EdTech · 3D · Product',
  },
  {
    name: 'Atlon.uz',
    kind: 'Youth platform',
    url: 'https://atlon.uz',
    year: 'Jul 2026 — present',
    status: 'active',
    featured: true,
    coverTone: 'green',
    description: 'A youth platform centered on leadership, volunteering and real-world project experience.',
    detail: 'LinkedIn lists 500+ participants, 50+ volunteers, 12 cities and 20+ events across its programs.',
    tech: 'Youth · Leadership · Community · Events',
  },
  {
    name: 'MentorGo',
    kind: 'Mentoring platform',
    url: 'https://mentorgo.uz',
    year: 'Dec 2024 — present',
    status: 'active',
    role: 'Co-Founder & CTO',
    featured: true,
    coverTone: 'teal',
    logo: '/media/projects/mentorgo/logo.webp',
    description: 'A platform connecting ambitious students with mentors who have won major international scholarships.',
    detail: 'Built with a four-person team; the platform reached 3,000+ users and facilitated hundreds of mentoring sessions.',
    tech: 'Web · Mentorship · Product · AI',
  },
  {
    name: 'Lumora',
    kind: 'IT case competitions',
    url: '',
    year: 'Jul 2025 — Dec 2025',
    status: 'archived',
    role: 'Co-Founder & Media Director',
    coverTone: 'orange',
    logo: '/media/projects/lumora/logo.webp',
    description: 'A national competition format where student teams solve real IT cases and defend working solutions.',
    detail: 'Organized 15 competitions across 10 regions, engaging 1,000+ students and partnering with industry organizations.',
    tech: 'Community · Events · Partnerships · Media',
  },
  {
    name: 'Friendship Checker Bot',
    kind: 'Telegram bot',
    url: '',
    year: 'Feb 2026',
    status: 'experiment',
    coverTone: 'red',
    description: 'A playful Telegram bot for personalized friendship quizzes, anonymous messages and compatibility checks.',
    detail: 'Designed as a viral-friendly social experiment with quiz sharing and leaderboards.',
    tech: 'Telegram bot · Viral loops · Product experiment',
  },
  {
    name: 'Quoteum',
    kind: 'Interactive web experiment',
    url: '',
    year: 'Jan 2026',
    status: 'experiment',
    coverTone: 'purple',
    description: 'A museum of quotes that lets visitors browse curated inspiration based on their mood.',
    detail: 'Built as a polished interactive experience with animation, navigation and an admin toolkit.',
    tech: 'Web · UI/UX · Content · Experiment',
  },
  {
    name: 'DavomatAI',
    kind: 'AI prototype',
    url: '',
    year: 'Jun 2024 — Jul 2024',
    status: 'archived',
    role: 'AI Researcher & Engineer',
    coverTone: 'blue',
    description: 'An AI-powered attendance system developed at New Uzbekistan University.',
    detail: 'The prototype reduced educators’ manual record-keeping by about four hours per month during the pilot.',
    tech: 'Computer vision · AI · Prototype',
  },
  {
    name: 'HospitalBookingCoom',
    kind: 'Health-tech platform',
    url: '',
    year: 'Feb 2024 — Jul 2024',
    status: 'archived',
    coverTone: 'teal',
    description: 'A hospital service booking project for consultations and operations.',
    detail: 'Built with a 14-person team of programmers, designers and researchers; the project was later stopped because of financial constraints.',
    tech: 'Web · Health-tech · Team project',
  },
  {
    name: 'Ijodkorlar Jamiyati',
    kind: 'Creator platform',
    url: '',
    year: 'Feb 2024 — Apr 2024',
    status: 'archived',
    coverTone: 'orange',
    description: 'A platform for creators to upload, showcase and share their work with a broader audience.',
    detail: 'An early community-building and product experiment focused on Uzbek creators.',
    tech: 'Web · Creators · Community',
  },
  {
    name: 'StartUpper',
    kind: 'Startup platform concept',
    url: '',
    year: 'Early project',
    status: 'experiment',
    coverTone: 'red',
    description: 'A platform concept for early-stage founders to collaborate and access startup opportunities.',
    detail: 'Focused on structured collaboration, startup team formation and opportunity discovery.',
    tech: 'Startups · Collaboration · Product concept',
  },
  {
    name: 'WebLaunch',
    kind: 'Business competition project',
    url: '',
    year: 'Dec 2024',
    status: 'archived',
    coverTone: 'green',
    description: 'A business project created for Target International School’s national business championship.',
    detail: 'Won 1st place among five school branches; Nurbek led strategy, development and presentation.',
    tech: 'Business · Product · Pitching',
  },
];

export const experiences: Experience[] = [
  {
    id: 'edugrands',
    organization: 'EduGrands',
    role: 'Founder & CEO',
    period: 'Aug 2023 — present',
    location: 'Uzbekistan',
    website: 'https://edugrants.uz',
    logo: '/media/projects/edugrands/logo.webp',
    description: 'Founded and scaled a scholarship-discovery platform and community connecting young people with verified international opportunities.',
    highlights: ['50,000+ users across the ecosystem', '$10,000+ revenue from advertising and partnerships', 'EduCast interview series and nationwide scholarship marathons'],
    relatedProject: 'EduGrands',
  },
  {
    id: 'empira',
    organization: 'Empira (JaydariTech)',
    role: 'Co-Founder & CEO',
    period: 'Sept 2026 — present',
    location: 'Uzbekistan',
    website: 'https://empira.uz',
    logo: '/media/projects/empira/logo.webp',
    description: 'Building an AI-powered virtual laboratory for school students.',
    highlights: ['Built from scratch in 72 hours', '1st place, National AI Hackathon — EdTech track', 'Earned a Startup Garage place and school rollout partnerships'],
    relatedProject: 'Empira',
  },
  {
    id: 'startup-ambassadors',
    organization: 'Startup Ambassadors',
    role: 'Project Manager',
    period: '2026',
    location: 'Youth Affairs Agency of Uzbekistan',
    website: 'https://www.startupambassadors.uz',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Startup_Ambassadors_2.png',
    description: 'Managed a nationwide youth startup network backed by the Youth Affairs Agency and Yoshlar Ventures.',
    highlights: ['Joined as assistant manager and later became Project Manager', 'Public LinkedIn update reports 500+ events and 10,000+ young people engaged', 'Received a Best Employee award during the placement'],
  },
  {
    id: 'digital-generation',
    organization: 'Digital Generation Uzbekistan',
    role: 'AI Mentor',
    period: 'Mar 2024 — present',
    location: 'Uzbekistan',
    website: 'https://digitalgeneration.uz',
    logo: 'https://digitalgeneration.uz/static/img/logo.png',
    description: 'Mentor and educator in national AI and no-code camps.',
    highlights: ['Mentored 350+ students across 4 national camps', 'Designed inclusive curriculum for underrepresented and disabled youth', 'Taught AI and no-code tools'],
  },
  {
    id: 'lumora',
    organization: 'Lumora',
    role: 'Co-Founder & Media Director',
    period: 'Jul 2025 — Dec 2025',
    location: 'Uzbekistan',
    website: 'https://t.me/thelumoraa',
    logo: '/media/projects/lumora/logo.webp',
    description: 'Co-built a national IT case competition community.',
    highlights: ['15 competitions across 10 regions', '1,000+ students engaged', '15 industry partners and 5,000+ online reach'],
    relatedProject: 'Lumora',
  },
  {
    id: 'mentorgo',
    organization: 'MentorGo',
    role: 'Co-Founder & CTO',
    period: 'Dec 2024 — Nov 2025',
    location: 'Uzbekistan',
    website: 'https://mentorgo.uz',
    logo: '/media/projects/mentorgo/logo.webp',
    description: 'Built the mentoring platform with a four-person team.',
    highlights: ['3,000+ users', '200+ monthly mentoring sessions during the period', 'Students collectively secured $1M+ in scholarships'],
    relatedProject: 'MentorGo',
  },
  {
    id: 'newuu',
    organization: 'New Uzbekistan University',
    role: 'AI Researcher & Engineer',
    period: 'Jun 2024 — Jul 2024',
    location: 'Tashkent, Uzbekistan',
    website: 'https://newuu.uz',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Logo_New_Uzbekistan_University.jpg/960px-Logo_New_Uzbekistan_University.jpg',
    description: 'Worked on applied AI research and engineering, including the DavomatAI attendance prototype.',
    highlights: ['Developed DavomatAI', 'Reduced manual attendance record-keeping by about 4 hours per month in the pilot'],
    relatedProject: 'DavomatAI',
  },
  {
    id: 'family-farm',
    organization: 'Family Farm',
    role: 'Co-Manager',
    period: 'Ongoing',
    location: 'Namangan, Uzbekistan',
    description: 'Co-manage a two-hectare apple orchard and sell harvest at the local bazaar.',
    highlights: ['Hands-on agriculture', 'Small-business operations', 'Local sales and harvest management'],
  },
];

export const awards: Award[] = [
  {year: '2026', name: 'National AI Hackathon — 1st Place, EdTech', issuer: 'National AI Hackathon', description: 'Led JaydariTech to first place with Empira after a 72-hour build.'},
  {year: '2026', name: '100M UZS Grant', issuer: 'Specialized Schools Agency', description: 'Project team secured a 100,000,000 UZS grant for an educational initiative.'},
  {year: '2026', name: 'Mirzo Ulug‘bek Vorislari — Republic Winner', issuer: 'National competition', description: 'Placed in the top 35 out of 48,000+ applicants across Uzbekistan.'},
  {year: '2025', name: 'TOP3 Project in Startup Day', issuer: 'IT Park Uzbekistan', description: 'MentorGo placed first among 25 projects in the referenced Startup Day competition.'},
  {year: '2025', name: 'LaunchX — 99% Scholarship', issuer: 'LaunchX', description: 'Received a 99% scholarship for the entrepreneurship programme.'},
  {year: '2024', name: '1st Place — Business Championship', issuer: 'Target International School', description: 'Won with WebLaunch among five school branches.'},
  {year: '2024', name: 'Full Tuition Scholarship', issuer: 'Target International School', description: 'Awarded a full annual school scholarship.'},
  {year: '2023', name: 'Top 100 Student of Uzbekistan', issuer: 'Ministry of Education', description: 'Recognized nationally for academics, leadership and contributions to education and tech.'},
  {year: '2023', name: 'Kelajak Yoshlari', issuer: 'Najot Ta’lim & Cambridge Learning Centre', description: 'Won full scholarships through the national selection programme.'},
  {year: '2021', name: 'Khiso Olympiad — Regional 1st Place', description: 'Placed first in the regional stage.'},
];

export const photos: Photo[] = [
  {
    id: 'achievements-100m-uzs-grant-01-grant-award',
    title: '100M UZS grant award',
    album: '100M UZS Grant',
    section: 'Achievements',
    src: '/media/achievements/100m-uzs-grant/01-grant-award.webp',
    date: '2026',
    caption: '100M UZS grant award.',
    alt: '100M UZS grant award',
    kind: 'photo',
    achievement: '100M UZS Grant',
  },
  {
    id: 'achievements-100m-uzs-grant-02-team-photo',
    title: 'Team photo after the grant',
    album: '100M UZS Grant',
    section: 'Achievements',
    src: '/media/achievements/100m-uzs-grant/02-team-photo.webp',
    date: '2026',
    caption: 'Team photo after the grant.',
    alt: 'Team photo after the grant',
    kind: 'photo',
    achievement: '100M UZS Grant',
  },
  {
    id: 'achievements-launchx-01-acceptance-email',
    title: 'LaunchX 2025 acceptance',
    album: 'LaunchX',
    section: 'Achievements',
    src: '/media/achievements/launchx/01-acceptance-email.webp',
    date: '2025',
    caption: 'LaunchX 2025 acceptance.',
    alt: 'LaunchX 2025 acceptance',
    kind: 'photo',
    achievement: 'LaunchX — 99% Scholarship',
  },
  {
    id: 'achievements-launchx-02-financial-support-email',
    title: 'LaunchX financial support update',
    album: 'LaunchX',
    section: 'Achievements',
    src: '/media/achievements/launchx/02-financial-support-email.webp',
    date: '2025',
    caption: 'LaunchX financial support update.',
    alt: 'LaunchX financial support update',
    kind: 'photo',
    achievement: 'LaunchX — 99% Scholarship',
  },
  {
    id: 'achievements-mirzo-ulugbek-vorislari-01-award-portrait',
    title: 'Mirzo Ulugbek Vorislari award portrait',
    album: 'Mirzo Ulugbek Vorislari',
    section: 'Achievements',
    src: '/media/achievements/mirzo-ulugbek-vorislari/01-award-portrait.webp',
    date: '2026',
    caption: 'Mirzo Ulugbek Vorislari award portrait.',
    alt: 'Mirzo Ulugbek Vorislari award portrait',
    kind: 'photo',
    achievement: 'Mirzo Ulug‘bek Vorislari — Republic Winner',
  },
  {
    id: 'achievements-mirzo-ulugbek-vorislari-02-team-award-photo',
    title: 'Mirzo Ulugbek Vorislari team award photo',
    album: 'Mirzo Ulugbek Vorislari',
    section: 'Achievements',
    src: '/media/achievements/mirzo-ulugbek-vorislari/02-team-award-photo.webp',
    date: '2026',
    caption: 'Mirzo Ulugbek Vorislari team award photo.',
    alt: 'Mirzo Ulugbek Vorislari team award photo',
    kind: 'photo',
    achievement: 'Mirzo Ulug‘bek Vorislari — Republic Winner',
  },
  {
    id: 'achievements-national-ai-hackathon-01-winners-photo',
    title: 'National AI Hackathon winners photo',
    album: 'National AI Hackathon',
    section: 'Achievements',
    src: '/media/achievements/national-ai-hackathon/01-winners-photo.webp',
    date: '2026',
    caption: 'National AI Hackathon winners photo.',
    alt: 'National AI Hackathon winners photo',
    kind: 'photo',
    project: 'Empira',
    achievement: 'National AI Hackathon — 1st Place, EdTech',
  },
  {
    id: 'achievements-national-ai-hackathon-02-team-selfie',
    title: 'National AI Hackathon team selfie',
    album: 'National AI Hackathon',
    section: 'Achievements',
    src: '/media/achievements/national-ai-hackathon/02-team-selfie.webp',
    date: '2026',
    caption: 'National AI Hackathon team selfie.',
    alt: 'National AI Hackathon team selfie',
    kind: 'photo',
    project: 'Empira',
    achievement: 'National AI Hackathon — 1st Place, EdTech',
  },
  {
    id: 'achievements-startup-day-01-event-photo',
    title: 'Startup Day event photo',
    album: 'Startup Day',
    section: 'Achievements',
    src: '/media/achievements/startup-day/01-event-photo.webp',
    date: '2025',
    caption: 'Startup Day event photo.',
    alt: 'Startup Day event photo',
    kind: 'photo',
    project: 'MentorGo',
    achievement: 'TOP3 Project in Startup Day',
  },
  {
    id: 'achievements-startup-day-02-award-photo',
    title: 'Startup Day award photo',
    album: 'Startup Day',
    section: 'Achievements',
    src: '/media/achievements/startup-day/02-award-photo.webp',
    date: '2025',
    caption: 'Startup Day award photo.',
    alt: 'Startup Day award photo',
    kind: 'photo',
    project: 'MentorGo',
    achievement: 'TOP3 Project in Startup Day',
  },
  {
    id: 'achievements-top-100-students-uzbekistan-01-national-group-photo',
    title: 'TOP 100 Students national group photo',
    album: 'TOP 100 Students Uzbekistan',
    section: 'Achievements',
    src: '/media/achievements/top-100-students-uzbekistan/01-national-group-photo.webp',
    date: '2023',
    caption: 'TOP 100 Students national group photo.',
    alt: 'TOP 100 Students national group photo',
    kind: 'photo',
    achievement: 'Top 100 Student of Uzbekistan',
  },
  {
    id: 'achievements-top-100-students-uzbekistan-02-award-ceremony',
    title: 'TOP 100 Students award ceremony',
    album: 'TOP 100 Students Uzbekistan',
    section: 'Achievements',
    src: '/media/achievements/top-100-students-uzbekistan/02-award-ceremony.webp',
    date: '2023',
    caption: 'TOP 100 Students award ceremony.',
    alt: 'TOP 100 Students award ceremony',
    kind: 'photo',
    achievement: 'Top 100 Student of Uzbekistan',
  },
  {
    id: 'achievements-acceptances-istanbul-youth-summit-01-acceptance-letter',
    title: 'Istanbul Youth Summit ambassador acceptance',
    album: 'Istanbul Youth Summit',
    section: 'Acceptances',
    src: '/media/achievements/acceptances/istanbul-youth-summit/01-acceptance-letter.webp',
    date: '2026',
    caption: 'Acceptance document from the portfolio archive.',
    alt: 'Istanbul Youth Summit ambassador acceptance',
    kind: 'document',
  },
  {
    id: 'achievements-acceptances-nyuad-university-prep-program-01-acceptance-letter',
    title: 'NYUAD University Prep Program acceptance',
    album: 'NYUAD University Prep Program',
    section: 'Acceptances',
    src: '/media/achievements/acceptances/nyuad-university-prep-program/01-acceptance-letter.webp',
    date: '2026',
    caption: 'Acceptance document from the portfolio archive.',
    alt: 'NYUAD University Prep Program acceptance',
    kind: 'document',
  },
  {
    id: 'achievements-acceptances-hong-kong-polytechnic-university-01-offer-letter-redacted',
    title: 'Hong Kong Polytechnic University offer',
    album: 'Hong Kong Polytechnic University',
    section: 'Acceptances',
    src: '/media/achievements/acceptances/hong-kong-polytechnic-university/01-offer-letter-redacted.webp',
    date: '2026',
    caption: 'Public-safe redacted offer letter.',
    alt: 'Hong Kong Polytechnic University offer',
    kind: 'document',
  },
  {
    id: 'achievements-acceptances-beijing-normal-hong-kong-baptist-university-01-offer-letter-redacted',
    title: 'BNBU conditional offer',
    album: 'Beijing Normal-Hong Kong Baptist University',
    section: 'Acceptances',
    src: '/media/achievements/acceptances/beijing-normal-hong-kong-baptist-university/01-offer-letter-redacted.webp',
    date: '2026',
    caption: 'Public-safe redacted offer letter.',
    alt: 'BNBU conditional offer',
    kind: 'document',
  },
  {
    id: 'achievements-acceptances-cuhk-shenzhen-01-offer-letter-redacted',
    title: 'CUHK-Shenzhen admission offer',
    album: 'CUHK-Shenzhen',
    section: 'Acceptances',
    src: '/media/achievements/acceptances/cuhk-shenzhen/01-offer-letter-redacted.webp',
    date: '2026',
    caption: 'Public-safe redacted offer letter.',
    alt: 'CUHK-Shenzhen admission offer',
    kind: 'document',
  },
  {
    id: 'achievements-acceptances-hkust-01-offer-letter-redacted',
    title: 'HKUST admission offer',
    album: 'HKUST',
    section: 'Acceptances',
    src: '/media/achievements/acceptances/hkust/01-offer-letter-redacted.webp',
    date: '2026',
    caption: 'Public-safe redacted offer letter.',
    alt: 'HKUST admission offer',
    kind: 'document',
  },
  {
    id: 'achievements-acceptances-university-of-alberta-01-offer-letter-redacted',
    title: 'University of Alberta admission offer',
    album: 'University of Alberta',
    section: 'Acceptances',
    src: '/media/achievements/acceptances/university-of-alberta/01-offer-letter-redacted.webp',
    date: '2026',
    caption: 'Public-safe redacted offer letter.',
    alt: 'University of Alberta admission offer',
    kind: 'document',
  },
  {
    id: 'achievements-acceptances-education-university-of-hong-kong-01-offer-letter-redacted',
    title: 'Education University of Hong Kong offer',
    album: 'Education University of Hong Kong',
    section: 'Acceptances',
    src: '/media/achievements/acceptances/education-university-of-hong-kong/01-offer-letter-redacted.webp',
    date: '2026',
    caption: 'Public-safe redacted offer letter.',
    alt: 'Education University of Hong Kong offer',
    kind: 'document',
  },
  {
    id: 'projects-edugrands-01-online-team-meeting',
    title: 'EduGrands online team meeting',
    album: 'EduGrands',
    section: 'Projects',
    src: '/media/projects/edugrands/01-online-team-meeting.webp',
    date: '2023 — present',
    caption: 'EduGrands online team meeting.',
    alt: 'EduGrands online team meeting',
    kind: 'photo',
    project: 'EduGrands',
  },
  {
    id: 'projects-edugrands-02-team-founders-cafe',
    title: 'EduGrands team at Founders Cafe',
    album: 'EduGrands',
    section: 'Projects',
    src: '/media/projects/edugrands/02-team-founders-cafe.webp',
    date: '2023 — present',
    caption: 'EduGrands team at Founders Cafe.',
    alt: 'EduGrands team at Founders Cafe',
    kind: 'photo',
    project: 'EduGrands',
  },
  {
    id: 'projects-edugrands-03-grants-marathon-poster',
    title: 'EduGrands Grants Marathon poster',
    album: 'EduGrands',
    section: 'Projects',
    src: '/media/projects/edugrands/03-grants-marathon-poster.webp',
    date: '2023 — present',
    caption: 'EduGrands Grants Marathon poster.',
    alt: 'EduGrands Grants Marathon poster',
    kind: 'poster',
    project: 'EduGrands',
  },
  {
    id: 'projects-edugrands-04-guest-speakers-poster',
    title: 'EduGrands guest speakers poster',
    album: 'EduGrands',
    section: 'Projects',
    src: '/media/projects/edugrands/04-guest-speakers-poster.webp',
    date: '2023 — present',
    caption: 'EduGrands guest speakers poster.',
    alt: 'EduGrands guest speakers poster',
    kind: 'poster',
    project: 'EduGrands',
  },
  {
    id: 'projects-lumora-01-team-photo',
    title: 'Lumora team photo',
    album: 'Lumora',
    section: 'Projects',
    src: '/media/projects/lumora/01-team-photo.webp',
    date: '2025',
    caption: 'Lumora team photo.',
    alt: 'Lumora team photo',
    kind: 'photo',
    project: 'Lumora',
  },
  {
    id: 'projects-lumora-02-competition-session',
    title: 'Lumora competition session',
    album: 'Lumora',
    section: 'Projects',
    src: '/media/projects/lumora/02-competition-session.webp',
    date: '2025',
    caption: 'Lumora competition session.',
    alt: 'Lumora competition session',
    kind: 'photo',
    project: 'Lumora',
  },
  {
    id: 'projects-lumora-03-participants-group',
    title: 'Lumora participants group photo',
    album: 'Lumora',
    section: 'Projects',
    src: '/media/projects/lumora/03-participants-group.webp',
    date: '2025',
    caption: 'Lumora participants group photo.',
    alt: 'Lumora participants group photo',
    kind: 'photo',
    project: 'Lumora',
  },
  {
    id: 'projects-lumora-04-closing-stage',
    title: 'Lumora closing stage photo',
    album: 'Lumora',
    section: 'Projects',
    src: '/media/projects/lumora/04-closing-stage.webp',
    date: '2025',
    caption: 'Lumora closing stage photo.',
    alt: 'Lumora closing stage photo',
    kind: 'photo',
    project: 'Lumora',
  },
  {
    id: 'experiences-events-digital-generation-uzbekistan-01-event-team-selfie',
    title: 'Digital Generation — Event Team Selfie',
    album: 'Digital Generation Uzbekistan',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/digital-generation-uzbekistan/01-event-team-selfie.webp',
    date: '2024 — present',
    caption: 'Digital Generation — Event Team Selfie.',
    alt: 'Digital Generation — Event Team Selfie',
    kind: 'photo',
    experience: 'digital-generation',
  },
  {
    id: 'experiences-events-digital-generation-uzbekistan-02-mentoring-workspace',
    title: 'Digital Generation — Mentoring Workspace',
    album: 'Digital Generation Uzbekistan',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/digital-generation-uzbekistan/02-mentoring-workspace.webp',
    date: '2024 — present',
    caption: 'Digital Generation — Mentoring Workspace.',
    alt: 'Digital Generation — Mentoring Workspace',
    kind: 'photo',
    experience: 'digital-generation',
  },
  {
    id: 'experiences-events-digital-generation-uzbekistan-03-event-networking',
    title: 'Digital Generation — Event Networking',
    album: 'Digital Generation Uzbekistan',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/digital-generation-uzbekistan/03-event-networking.webp',
    date: '2024 — present',
    caption: 'Digital Generation — Event Networking.',
    alt: 'Digital Generation — Event Networking',
    kind: 'photo',
    experience: 'digital-generation',
  },
  {
    id: 'experiences-events-digital-generation-uzbekistan-04-mentor-session',
    title: 'Digital Generation — Mentor Session',
    album: 'Digital Generation Uzbekistan',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/digital-generation-uzbekistan/04-mentor-session.webp',
    date: '2024 — present',
    caption: 'Digital Generation — Mentor Session.',
    alt: 'Digital Generation — Mentor Session',
    kind: 'photo',
    experience: 'digital-generation',
  },
  {
    id: 'experiences-events-digital-generation-uzbekistan-05-guest-mentor-photo',
    title: 'Digital Generation — Guest Mentor Photo',
    album: 'Digital Generation Uzbekistan',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/digital-generation-uzbekistan/05-guest-mentor-photo.webp',
    date: '2024 — present',
    caption: 'Digital Generation — Guest Mentor Photo.',
    alt: 'Digital Generation — Guest Mentor Photo',
    kind: 'photo',
    experience: 'digital-generation',
  },
  {
    id: 'experiences-events-digital-generation-uzbekistan-06-classroom-session',
    title: 'Digital Generation — Classroom Session',
    album: 'Digital Generation Uzbekistan',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/digital-generation-uzbekistan/06-classroom-session.webp',
    date: '2024 — present',
    caption: 'Digital Generation — Classroom Session.',
    alt: 'Digital Generation — Classroom Session',
    kind: 'photo',
    experience: 'digital-generation',
  },
  {
    id: 'experiences-events-digital-generation-uzbekistan-07-building-at-camp',
    title: 'Digital Generation — Building At Camp',
    album: 'Digital Generation Uzbekistan',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/digital-generation-uzbekistan/07-building-at-camp.webp',
    date: '2024 — present',
    caption: 'Digital Generation — Building At Camp.',
    alt: 'Digital Generation — Building At Camp',
    kind: 'photo',
    experience: 'digital-generation',
  },
  {
    id: 'experiences-events-hackathons-01-team-arrival',
    title: 'Hackathon — Team Arrival',
    album: 'Hackathons',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/hackathons/01-team-arrival.webp',
    date: 'Archive',
    caption: 'Hackathon — Team Arrival.',
    alt: 'Hackathon — Team Arrival',
    kind: 'photo',
  },
  {
    id: 'experiences-events-hackathons-02-prize-photo',
    title: 'Hackathon — Prize Photo',
    album: 'Hackathons',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/hackathons/02-prize-photo.webp',
    date: 'Archive',
    caption: 'Hackathon — Prize Photo.',
    alt: 'Hackathon — Prize Photo',
    kind: 'photo',
  },
  {
    id: 'experiences-events-hackathons-03-building-session',
    title: 'Hackathon — Building Session',
    album: 'Hackathons',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/hackathons/03-building-session.webp',
    date: 'Archive',
    caption: 'Hackathon — Building Session.',
    alt: 'Hackathon — Building Session',
    kind: 'photo',
  },
  {
    id: 'experiences-events-hackathons-04-event-team-photo',
    title: 'Hackathon — Event Team Photo',
    album: 'Hackathons',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/hackathons/04-event-team-photo.webp',
    date: 'Archive',
    caption: 'Hackathon — Event Team Photo.',
    alt: 'Hackathon — Event Team Photo',
    kind: 'photo',
  },
  {
    id: 'experiences-events-hogwarts-camp-01-presentation',
    title: 'Hogwarts Camp — Presentation',
    album: 'Hogwarts Camp',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/hogwarts-camp/01-presentation.webp',
    date: 'Archive',
    caption: 'Hogwarts Camp — Presentation.',
    alt: 'Hogwarts Camp — Presentation',
    kind: 'photo',
  },
  {
    id: 'experiences-events-hogwarts-camp-02-graduation-team',
    title: 'Hogwarts Camp — Graduation Team',
    album: 'Hogwarts Camp',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/hogwarts-camp/02-graduation-team.webp',
    date: 'Archive',
    caption: 'Hogwarts Camp — Graduation Team.',
    alt: 'Hogwarts Camp — Graduation Team',
    kind: 'photo',
  },
  {
    id: 'experiences-events-hogwarts-camp-03-graduation-group',
    title: 'Hogwarts Camp — Graduation Group',
    album: 'Hogwarts Camp',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/hogwarts-camp/03-graduation-group.webp',
    date: 'Archive',
    caption: 'Hogwarts Camp — Graduation Group.',
    alt: 'Hogwarts Camp — Graduation Group',
    kind: 'photo',
  },
  {
    id: 'experiences-events-hogwarts-camp-06-campus-memory',
    title: 'Hogwarts Camp — Campus Memory',
    album: 'Hogwarts Camp',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/hogwarts-camp/06-campus-memory.webp',
    date: 'Archive',
    caption: 'Hogwarts Camp — Campus Memory.',
    alt: 'Hogwarts Camp — Campus Memory',
    kind: 'photo',
  },
  {
    id: 'experiences-events-hogwarts-camp-04-research-club-moment',
    title: 'Hogwarts Camp — Research Club Moment',
    album: 'Hogwarts Camp',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/hogwarts-camp/04-research-club-moment.webp',
    date: 'Archive',
    caption: 'Hogwarts Camp — Research Club Moment.',
    alt: 'Hogwarts Camp — Research Club Moment',
    kind: 'photo',
  },
  {
    id: 'experiences-events-hogwarts-camp-05-full-group-photo',
    title: 'Hogwarts Camp — Full Group Photo',
    album: 'Hogwarts Camp',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/hogwarts-camp/05-full-group-photo.webp',
    date: 'Archive',
    caption: 'Hogwarts Camp — Full Group Photo.',
    alt: 'Hogwarts Camp — Full Group Photo',
    kind: 'photo',
  },
  {
    id: 'experiences-events-school-events-01-nis-campus-portrait',
    title: 'School — Nis Campus Portrait',
    album: 'School Events',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/school-events/01-nis-campus-portrait.webp',
    date: 'Archive',
    caption: 'School — Nis Campus Portrait.',
    alt: 'School — Nis Campus Portrait',
    kind: 'photo',
  },
  {
    id: 'experiences-events-school-events-02-from-idea-to-architecture-talk',
    title: 'School — From Idea To Architecture Talk',
    album: 'School Events',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/school-events/02-from-idea-to-architecture-talk.webp',
    date: 'Archive',
    caption: 'School — From Idea To Architecture Talk.',
    alt: 'School — From Idea To Architecture Talk',
    kind: 'photo',
  },
  {
    id: 'experiences-events-school-events-03-from-idea-to-architecture-poster',
    title: 'School — From Idea To Architecture Poster',
    album: 'School Events',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/school-events/03-from-idea-to-architecture-poster.webp',
    date: 'Archive',
    caption: 'School — From Idea To Architecture Poster.',
    alt: 'School — From Idea To Architecture Poster',
    kind: 'photo',
  },
  {
    id: 'experiences-events-school-events-04-school-workshop',
    title: 'School — School Workshop',
    album: 'School Events',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/school-events/04-school-workshop.webp',
    date: 'Archive',
    caption: 'School — School Workshop.',
    alt: 'School — School Workshop',
    kind: 'photo',
  },
  {
    id: 'experiences-events-startup-ambassadors-01-project-meeting',
    title: 'Startup Ambassadors — Project Meeting',
    album: 'Startup Ambassadors',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/startup-ambassadors/01-project-meeting.webp',
    date: '2026',
    caption: 'Startup Ambassadors — Project Meeting.',
    alt: 'Startup Ambassadors — Project Meeting',
    kind: 'photo',
    experience: 'startup-ambassadors',
  },
  {
    id: 'experiences-events-startup-ambassadors-02-presentation-screen',
    title: 'Startup Ambassadors — Presentation Screen',
    album: 'Startup Ambassadors',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/startup-ambassadors/02-presentation-screen.webp',
    date: '2026',
    caption: 'Startup Ambassadors — Presentation Screen.',
    alt: 'Startup Ambassadors — Presentation Screen',
    kind: 'photo',
    experience: 'startup-ambassadors',
  },
  {
    id: 'experiences-events-startup-ambassadors-03-founders-cafe-team',
    title: 'Startup Ambassadors — Founders Cafe Team',
    album: 'Startup Ambassadors',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/startup-ambassadors/03-founders-cafe-team.webp',
    date: '2026',
    caption: 'Startup Ambassadors — Founders Cafe Team.',
    alt: 'Startup Ambassadors — Founders Cafe Team',
    kind: 'photo',
    experience: 'startup-ambassadors',
  },
  {
    id: 'experiences-events-team-photos-01-team-outdoors',
    title: 'Team — Team Outdoors',
    album: 'Team Photos',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/team-photos/01-team-outdoors.webp',
    date: 'Archive',
    caption: 'Team — Team Outdoors.',
    alt: 'Team — Team Outdoors',
    kind: 'photo',
  },
  {
    id: 'experiences-events-team-photos-02-team-work-session',
    title: 'Team — Team Work Session',
    album: 'Team Photos',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/team-photos/02-team-work-session.webp',
    date: 'Archive',
    caption: 'Team — Team Work Session.',
    alt: 'Team — Team Work Session',
    kind: 'photo',
  },
  {
    id: 'experiences-events-conferences-workshops-speaking-01-event-portrait',
    title: 'Event — Event Portrait',
    album: 'Conferences, Workshops & Speaking',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/conferences-workshops-and-speaking/01-event-portrait.webp',
    date: 'Archive',
    caption: 'Event — Event Portrait.',
    alt: 'Event — Event Portrait',
    kind: 'photo',
  },
  {
    id: 'experiences-events-conferences-workshops-speaking-02-event-team',
    title: 'Event — Event Team',
    album: 'Conferences, Workshops & Speaking',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/conferences-workshops-and-speaking/02-event-team.webp',
    date: 'Archive',
    caption: 'Event — Event Team.',
    alt: 'Event — Event Team',
    kind: 'photo',
  },
  {
    id: 'experiences-events-conferences-workshops-speaking-03-conference-floor',
    title: 'Event — Conference Floor',
    album: 'Conferences, Workshops & Speaking',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/conferences-workshops-and-speaking/03-conference-floor.webp',
    date: 'Archive',
    caption: 'Event — Conference Floor.',
    alt: 'Event — Conference Floor',
    kind: 'photo',
  },
  {
    id: 'experiences-events-conferences-workshops-speaking-04-conference-team',
    title: 'Event — Conference Team',
    album: 'Conferences, Workshops & Speaking',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/conferences-workshops-and-speaking/04-conference-team.webp',
    date: 'Archive',
    caption: 'Event — Conference Team.',
    alt: 'Event — Conference Team',
    kind: 'photo',
  },
  {
    id: 'experiences-events-conferences-workshops-speaking-05-technology-expo',
    title: 'Event — Technology Expo',
    album: 'Conferences, Workshops & Speaking',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/conferences-workshops-and-speaking/05-technology-expo.webp',
    date: 'Archive',
    caption: 'Event — Technology Expo.',
    alt: 'Event — Technology Expo',
    kind: 'photo',
  },
  {
    id: 'experiences-events-conferences-workshops-speaking-06-microsoft-event',
    title: 'Event — Microsoft Event',
    album: 'Conferences, Workshops & Speaking',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/conferences-workshops-and-speaking/06-microsoft-event.webp',
    date: 'Archive',
    caption: 'Event — Microsoft Event.',
    alt: 'Event — Microsoft Event',
    kind: 'photo',
  },
  {
    id: 'experiences-events-conferences-workshops-speaking-07-speaking-on-stage',
    title: 'Event — Speaking On Stage',
    album: 'Conferences, Workshops & Speaking',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/conferences-workshops-and-speaking/07-speaking-on-stage.webp',
    date: 'Archive',
    caption: 'Event — Speaking On Stage.',
    alt: 'Event — Speaking On Stage',
    kind: 'photo',
  },
  {
    id: 'experiences-events-conferences-workshops-speaking-08-networking-selfie',
    title: 'Event — Networking Selfie',
    album: 'Conferences, Workshops & Speaking',
    section: 'Experiences & Events',
    src: '/media/experiences-and-events/conferences-workshops-and-speaking/08-networking-selfie.webp',
    date: 'Archive',
    caption: 'Event — Networking Selfie.',
    alt: 'Event — Networking Selfie',
    kind: 'photo',
  },
];
